import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navigation from "./home/navigationbar";
import Footer from "./home/footersection";
import FloatingButtons from "./home/whatsapp";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "JSR Engineering Solution",
  description: "Generated by JSR Engineering Solution",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Navigation />
        {children}
        <Footer />
        <FloatingButtons />
      </body>
    </html>
  );
}
